var member = [
  { "name": "张伟", "email": "zhang.wei@example.com", "skill": "Frontend Developer" },
  { "name": "李娜", "email": "li.na@example.com", "skill": "Backend Developer" },
  { "name": "王磊", "email": "wang.lei@example.com", "skill": "Full Stack Developer" },
  { "name": "刘洋", "email": "liu.yang@example.com", "skill": "DevOps Engineer" },
  { "name": "陈静", "email": "chen.jing@example.com", "skill": "Data Scientist" },
  { "name": "杨军", "email": "yang.jun@example.com", "skill": "UI/UX Designer" },
  { "name": "张艳", "email": "zhang.yan@example.com", "skill": "Quality Assurance Engineer" },
  { "name": "李伟", "email": "li.wei@example.com", "skill": "Database Administrator" },
  { "name": "王芳", "email": "wang.fang@example.com", "skill": "Mobile App Developer" },
  { "name": "刘敏", "email": "liu.min@example.com", "skill": "Security Analyst" },
  { "name": "赵敏", "email": "zhao.min@example.com", "skill": "Blockchain Developer" },
  { "name": "周杰", "email": "zhou.jie@example.com", "skill": "Embedded Systems Engineer" },
  { "name": "吴涛", "email": "wu.tao@example.com", "skill": "Machine Learning Engineer" },
  { "name": "郑明", "email": "zheng.ming@example.com", "skill": "Cloud Solutions Architect" },
  { "name": "王丽", "email": "wang.li@example.com", "skill": "Data Analyst" },
  { "name": "徐涛", "email": "xu.tao@example.com", "skill": "Web Developer" },
  { "name": "孙杰", "email": "sun.jie@example.com", "skill": "System Administrator" },
  { "name": "李强", "email": "li.qiang@example.com", "skill": "Network Engineer" },
  { "name": "张敏", "email": "zhang.min@example.com", "skill": "Product Manager" },
  { "name": "王涛", "email": "wang.tao@example.com", "skill": "DevSecOps Engineer" },
  { "name": "陈磊", "email": "chen.lei@example.com", "skill": "Software Tester" },
  { "name": "杨娜", "email": "yang.na@example.com", "skill": "Technical Writer" },
  { "name": "赵杰", "email": "zhao.jie@example.com", "skill": "Graphic Designer" },
  { "name": "黄勇", "email": "huang.yong@example.com", "skill": "SEO Specialist" },
  { "name": "周娜", "email": "zhou.na@example.com", "skill": "IT Support Specialist" },
  { "name": "吴杰", "email": "wu.jie@example.com", "skill": "Business Analyst" },
  { "name": "郑涛", "email": "zheng.tao@example.com", "skill": "Scrum Master" },
  { "name": "王敏", "email": "wang.min@example.com", "skill": "VR Developer" },
  { "name": "徐杰", "email": "xu.jie@example.com", "skill": "AI Developer" },
  { "name": "孙强", "email": "sun.qiang@example.com", "skill": "IoT Developer" },
  { "name": "李勇", "email": "li.yong@example.com", "skill": "Game Developer" },
  { "name": "张磊", "email": "zhang.lei@example.com", "skill": "Cybersecurity Expert" },
  { "name": "王强", "email": "wang.qiang@example.com", "skill": "Technical Architect" },
  { "name": "陈杰", "email": "chen.jie@example.com", "skill": "Big Data Engineer" },
  { "name": "杨强", "email": "yang.qiang@example.com", "skill": "DevOps Consultant" },
  { "name": "赵磊", "email": "zhao.lei@example.com", "skill": "Cloud Developer" },
  { "name": "周勇", "email": "zhou.yong@example.com", "skill": "Hardware Engineer" },
  { "name": "吴强", "email": "wu.qiang@example.com", "skill": "Systems Analyst" },
  { "name": "郑杰", "email": "zheng.jie@example.com", "skill": "E-commerce Specialist" },
  { "name": "王杰", "email": "wang.jie@example.com", "skill": "Digital Marketer" },
  { "name": "徐强", "email": "xu.qiang@example.com", "skill": "Software Architect" },
  { "name": "孙涛", "email": "sun.tao@example.com", "skill": "Data Engineer" },
  { "name": "李杰", "email": "li.jie@example.com", "skill": "Frontend Architect" },
  { "name": "张强", "email": "zhang.qiang@example.com", "skill": "Backend Architect" },
  { "name": "王勇", "email": "wang.yong@example.com", "skill": "User Researcher" },
  { "name": "陈强", "email": "chen.qiang@example.com", "skill": "UX/UI Developer" },
  { "name": "杨杰", "email": "yang.jie@example.com", "skill": "Accessibility Expert" },
  { "name": "赵强", "email": "zhao.qiang@example.com", "skill": "Technical Project Manager" },
  { "name": "周涛", "email": "zhou.tao@example.com", "skill": "Software Engineering Manager" }
];
